version: "3.9"

services:
    fontissofontti:
        build:
            context: ./frontend
        ports:
            - "80:80"
        environment:
            - BACKEND_URL=http://backend:${PORT}
            - MINIO_URL=http://minio:9000
        depends_on:
            - backend
            - minio

    backend:
        build:
            context: ./backend
        ports:
            - "${PORT}:${PORT}"
        environment:
            - PORT=${PORT}
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASWORD}@localhost/${POSTGRES_DATABASE}
            - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
            - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
            - MINIO_HOST=minio
            - JWT_SECRET=${JWT_SECRET}
        depends_on:
            - minio
            - database

    minio:
        image: minio/minio
        ports:
            - "9000:9000"
        volumes:
            - minio:/data
        environment:
            - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
            - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
        command: server /data

    database:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_DATABASE: ${POSTGRES_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
    minio: {}
    database: {}
