version: "3.9"

services:
    frontendo:
        build:
            context: ./frontend
        ports:
            - "80:80"
        environment:
            - BACKEND_URL=http://backend:${PORT}
            - MINIO_URL=http://minio:9000
        networks:
            - lauta_network
        depends_on:
            - backend
            - minio

    backend:
        build:
            context: ./backend
        ports:
            - "${PORT}:${PORT}"
        environment:
            - PORT=${PORT}
            - MONGODB_URI=mongodb://mongo:27017
            - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
            - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
            - MINIO_HOST=minio
            - JWT_SECRET=${JWT_SECRET}
        networks:
            - lauta_network
        depends_on:
            - minio
            - mongo

    minio:
        image: minio/minio
        ports:
            - "9000:9000"
        volumes:
            - lauta_minio:/data
        environment:
            - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
            - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
        networks:
            - lauta_network
        command: server /data

    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - lauta_database:/data/db
        networks:
            - lauta_network

networks:
    lauta_network:

volumes:
    lauta_minio: {}
    lauta_database: {}
