version: "3.9"

services:
    minio:
        image: minio/minio
        ports:
            - 9000:9000
        volumes:
            - minio:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        command: server /data
    database:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_DATABASE: ${POSTGRES_DATABASE}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
    minio: {}
    database: {}
