version: "3.9"

services:
    minio:
        image: minio/minio
        ports:
            - 9000:9000
        volumes:
            - minio:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        command: server /data
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db

volumes:
    minio: {}
    mongo: {}
